import { useEffect, useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuth } from '../auth/auth-context'
import { DataLabel } from '../components/DataLabel'
import { apiRequest } from '../lib/api'
import { formatMoney, formatPercent } from '../lib/format'
import type { InstrumentDetail } from '../types/instrument'
import type { InstrumentPaperTrade, PaperAccount } from '../types/paper'

type State = { status: 'loading' } | { status: 'error'; message: string } | { status: 'empty' } | { status: 'ready'; instrument: InstrumentDetail; account: PaperAccount }

export function InstrumentInvestPage() {
  const auth = useAuth(); const token = auth.accessToken; const [params] = useSearchParams(); const instrumentId = params.get('instrument'); const [state, setState] = useState<State>(instrumentId ? { status: 'loading' } : { status: 'empty' }); const [amount, setAmount] = useState(''); const [submitting, setSubmitting] = useState(false); const [trade, setTrade] = useState<InstrumentPaperTrade | null>(null); const [message, setMessage] = useState<string | null>(null)
  useEffect(() => {
    if (!token || !instrumentId) return
    const controller = new AbortController(); const headers = { Authorization: `Bearer ${token}` }
    Promise.all([apiRequest<PaperAccount[]>('/paper-accounts', { headers, signal: controller.signal }), apiRequest<InstrumentDetail>(`/instruments/${instrumentId}?history_limit=120`, { signal: controller.signal })]).then(async ([accounts, instrument]) => { const listed = instrument.instrument_kind === 'listed_security'; const currency = listed ? instrument.currency : 'USD'; let account = listed ? accounts.find((candidate) => candidate.base_currency === currency) : accounts.at(0); if (!account) account = await apiRequest<PaperAccount>('/paper-accounts', { method: 'POST', headers, body: JSON.stringify({ name: listed ? `${currency} Listed Securities` : 'Global Paper Portfolio', base_currency: currency, starting_cash: '100000' }) }); setState({ status: 'ready', instrument, account }) }).catch((error: unknown) => { if (error instanceof DOMException && error.name === 'AbortError') return; setState({ status: 'error', message: error instanceof Error ? error.message : 'Paper instrument is unavailable.' }) })
    return () => controller.abort()
  }, [instrumentId, token])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || state.status !== 'ready') return; setSubmitting(true); setMessage(null); try { const result = await apiRequest<InstrumentPaperTrade>(`/paper-accounts/${state.account.id}/instrument-orders`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: JSON.stringify({ instrument_id: state.instrument.id, side: 'buy', amount }) }); setTrade(result); setState({ ...state, account: { ...state.account, cash_balance: String(Number(state.account.cash_balance) - Number(result.gross_amount)) } }); setMessage('Paper market position opened.') } catch (error) { setMessage(error instanceof Error ? error.message : 'The paper order could not be completed.') } finally { setSubmitting(false) } }
  if (state.status === 'loading') return <main className="lab-state">Preparing the market contract…</main>
  if (state.status === 'error') return <main className="lab-state lab-state--error">{state.message}</main>
  if (state.status === 'empty') return <main className="simulate-empty"><DataLabel>05 / Paper markets</DataLabel><h1>Select a<br />market first.</h1><Link to="/">Open global markets ↗</Link></main>
  const latest = state.instrument.history.at(0); const oldest = state.instrument.history.at(-1); const listed = state.instrument.instrument_kind === 'listed_security'; const seriesChange = latest?.annual_change_percent ?? (latest && oldest && latest !== oldest ? String((Number(latest.value) / Number(oldest.value) - 1) * 100) : null); const exposure = amount ? Number(amount) / Number(state.account.cash_balance) * 100 : null
  return <main className="simulate-page instrument-invest-page"><section className="simulate-context"><DataLabel>05 / Paper market contract</DataLabel><p>{state.instrument.country_code} / {listed ? 'LISTED REAL ESTATE SECURITY' : 'OFFICIAL RESIDENTIAL INDEX'}</p><h1>{state.instrument.name}</h1><div><span><DataLabel>{listed ? 'Latest EOD close' : 'Latest index mark'}</DataLabel><strong>{latest ? (listed ? formatMoney(latest.value, latest.currency) : `${Number(latest.value).toFixed(2)} pts`) : '—'}</strong></span><span><DataLabel>{latest?.annual_change_percent ? '12M movement' : 'Available-series movement'}</DataLabel><strong>{formatPercent(seriesChange)}</strong></span></div></section><section className="order-ticket"><DataLabel>Open paper position</DataLabel><h2>Put capital<br />behind the view.</h2><dl><div><dt>Available demo cash</dt><dd>{formatMoney(state.account.cash_balance, state.account.base_currency)}</dd></div><div><dt>Settlement</dt><dd>{state.account.base_currency} demo cash</dd></div><div><dt>Exposure after order</dt><dd>{exposure === null ? '—' : `${exposure.toFixed(2)}%`}</dd></div><div><dt>Verified observation</dt><dd>{latest?.observed_on ?? '—'}</dd></div></dl>{trade ? <div className="order-confirmation"><DataLabel>Position opened</DataLabel><strong>{formatMoney(trade.gross_amount, trade.settlement_currency)}</strong><span>{Number(trade.units).toFixed(6)} {listed ? 'paper shares' : 'synthetic units'} at {listed ? formatMoney(trade.execution_price, trade.settlement_currency) : `${Number(trade.execution_price).toFixed(2)} index points`}</span><Link to="/portfolio">View portfolio ↗</Link></div> : <form onSubmit={submit}><label><span>Virtual investment / {state.account.base_currency}</span><input required min="0.01" max={state.account.cash_balance} step="0.01" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" /></label><button disabled={submitting} type="submit">{submitting ? 'Opening position…' : 'Open paper position'}</button></form>}{message && <p className="order-message">{message}</p>}<p className="paper-disclosure">{listed ? 'Development simulation using source-backed end-of-day closes. No security is purchased; the prototype quote feed is not licensed for production redistribution.' : 'Simulation only. The position follows a verified market index. No property, security, fund, or financial instrument is purchased.'}</p></section></main>
}
