import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { DataLabel } from '../components/DataLabel'
import { apiRequest } from '../lib/api'
import { formatPercent } from '../lib/format'
import type { InstrumentDetail, InstrumentPage, InvestmentInstrument } from '../types/instrument'

type LoadState = { status: 'loading' } | { status: 'error'; message: string } | { status: 'ready'; instruments: InvestmentInstrument[] }
interface ComparisonSeries { instrument: InvestmentInstrument; detail: InstrumentDetail; points: { date: string; value: number }[]; change: number | null }
const SERIES_COLORS = ['#79e7a0', '#f4cf65', '#74a7ff', '#e98f72', '#b78cff']

export function MarketComparisonPage() {
  const [load, setLoad] = useState<LoadState>({ status: 'loading' }); const [ids, setIds] = useState<string[]>([]); const [series, setSeries] = useState<ComparisonSeries[] | null>(null); const [message, setMessage] = useState<string | null>(null); const [running, setRunning] = useState(false)
  useEffect(() => { const controller = new AbortController(); apiRequest<InstrumentPage>('/instruments?kind=market_proxy&status=paper_tradeable&provider_slug=bis-rpp&limit=100', { signal: controller.signal }).then((page) => setLoad({ status: 'ready', instruments: page.items })).catch((error: unknown) => { if (error instanceof DOMException && error.name === 'AbortError') return; setLoad({ status: 'error', message: error instanceof Error ? error.message : 'Global instruments are unavailable.' }) }); return () => controller.abort() }, [])
  const selected = useMemo(() => load.status === 'ready' ? load.instruments.filter((instrument) => ids.includes(instrument.id)) : [], [load, ids])
  function toggle(id: string) { setSeries(null); setMessage(null); setIds((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < 5 ? [...current, id] : current) }
  async function compare() {
    if (ids.length < 2) return; setRunning(true); setMessage(null)
    try { const details = await Promise.all(ids.map((id) => apiRequest<InstrumentDetail>(`/instruments/${id}?history_limit=120`))); setSeries(details.map((detail): ComparisonSeries => { const chronological = [...detail.history].reverse(); const base = Number(chronological.at(0)?.value); const points = chronological.filter((observation) => Number.isFinite(Number(observation.value)) && base > 0).map((observation) => ({ date: observation.observed_on, value: Number(observation.value) / base * 100 })); const latest = points.at(-1)?.value; const latestObservation = detail.history.at(0); const instrument = selected.find((candidate) => candidate.id === detail.id) ?? { ...detail, observed_on: latestObservation?.observed_on ?? null, value: latestObservation?.value ?? null, annual_change_percent: latestObservation?.annual_change_percent ?? null, income_yield_percent: latestObservation?.income_yield_percent ?? null }; return { instrument, detail, points, change: latest === undefined ? null : latest - 100 } })) } catch (error) { setMessage(error instanceof Error ? error.message : 'Comparison could not be calculated.') } finally { setRunning(false) }
  }
  return <main className="comparison-page"><header className="comparison-header"><div><DataLabel>01 / Global market comparison</DataLabel><h1>Compare<br />the world.</h1></div><p>Official residential property indices are rebased to 100 at the beginning of the selected history. This compares market movement—not property prices, currencies, or investible offers.</p></header>{load.status === 'loading' && <ComparisonState>Loading official global instruments…</ComparisonState>}{load.status === 'error' && <ComparisonState error>{load.message}</ComparisonState>}{load.status === 'ready' && <><section className="comparison-controls"><div><DataLabel>Selected instruments / {ids.length} of 5</DataLabel><div>{selected.map((instrument) => <button key={instrument.id} type="button" onClick={() => toggle(instrument.id)}>{instrument.country_code} ×</button>)}</div></div><div className="comparison-method"><span>Measure</span><strong>INDEX / BASE 100</strong></div><button type="button" disabled={ids.length < 2 || running} onClick={compare}>{running ? 'Normalizing…' : 'Run comparison ↗'}</button></section><section className="comparison-market-picker"><div className="comparison-picker-head"><span>Market instrument</span><span>Latest index</span><span>12M growth</span><span>History</span><span>Select</span></div>{load.instruments.map((instrument) => <button className={ids.includes(instrument.id) ? 'is-selected' : ''} type="button" onClick={() => toggle(instrument.id)} key={instrument.id}><span><strong>{shortName(instrument.name)}</strong><small>{instrument.country_code} / BIS OFFICIAL MARKET PROXY</small></span><span>{instrument.value === null ? '—' : Number(instrument.value).toFixed(2)}</span><span className={Number(instrument.annual_change_percent) >= 0 ? 'signal--positive' : 'signal--negative'}>{formatPercent(instrument.annual_change_percent)}</span><span>{instrument.observed_on ?? '—'}</span><i>{ids.includes(instrument.id) ? 'Selected' : 'Select'}</i></button>)}</section>{message && <p className="comparison-message" role="alert">{message}</p>}{series && <ComparisonResult series={series} />}</>}</main>
}

function ComparisonResult({ series }: { series: ComparisonSeries[] }) {
  const allValues = series.flatMap((item) => item.points.map((point) => point.value)); const min = Math.min(...allValues, 100); const max = Math.max(...allValues, 100); const range = Math.max(max - min, 1)
  return <section className="comparison-result comparison-result--instrument"><div className="section-heading"><div><DataLabel>Normalized performance / base 100</DataLabel><h2>Market against market.</h2></div><span>{series.length} official series</span></div><div className="comparison-chart"><svg viewBox="0 0 1000 430" preserveAspectRatio="none" role="img" aria-label="Normalized property market performance comparison">{[0, .25, .5, .75, 1].map((fraction) => <line key={fraction} x1="0" x2="1000" y1={30 + fraction * 360} y2={30 + fraction * 360} />)}{series.map((item, seriesIndex) => { const path = item.points.map((point, index) => { const x = item.points.length <= 1 ? 0 : index / (item.points.length - 1) * 1000; const y = 390 - (point.value - min) / range * 360; return `${index ? 'L' : 'M'}${x.toFixed(2)},${y.toFixed(2)}` }).join(' '); return <path key={item.instrument.id} d={path} style={{ stroke: SERIES_COLORS[seriesIndex] }} /> })}</svg><div className="comparison-chart__axis"><span>{series.at(0)?.points.at(0)?.date.slice(0, 4)}</span><span>OFFICIAL QUARTERLY OBSERVATIONS</span><span>{series.at(0)?.points.at(-1)?.date.slice(0, 4)}</span></div></div><div className="comparison-series-ledger">{series.map((item, index) => <article key={item.instrument.id}><i style={{ background: SERIES_COLORS[index] }} /><div><strong>{shortName(item.instrument.name)}</strong><small>{item.instrument.country_code} / {item.points.length} observations</small></div><span className={(item.change ?? 0) >= 0 ? 'signal--positive' : 'signal--negative'}>{formatPercent(item.change === null ? null : String(item.change))}</span><em>{item.detail.history.at(0)?.observed_on ?? '—'}</em><Link to={`/paper-invest?instrument=${item.instrument.id}`}>Paper invest ↗</Link></article>)}</div><p className="comparison-disclosure">Paper research only. Each line is an official national residential property-price index normalized to expose relative movement. It is not a quote, forecast, security, or promise of return.</p></section>
}
function shortName(name: string) { return name.replace(' Residential Property Price Index', '') }
function ComparisonState({ children, error = false }: { children: string; error?: boolean }) { return <div className={`comparison-state${error ? ' comparison-state--error' : ''}`}>{children}</div> }
