import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { DataLabel } from '../components/DataLabel'
import { apiRequest } from '../lib/api'
import { formatMoney, formatPercent } from '../lib/format'
import type { PropertyScore } from '../types/property'
import type { MarketDetail, MarketMetric } from '../types/market'

type State = { status: 'loading' } | { status: 'error'; message: string } | { status: 'ready'; market: MarketDetail; score: PropertyScore }
export function MarketDetailPage() {
  const { id } = useParams(); const [state, setState] = useState<State>({ status: 'loading' })
  useEffect(() => { if (!id) return; const controller = new AbortController(); Promise.all([apiRequest<MarketDetail>(`/markets/${id}?history_limit=120`, { signal: controller.signal }), apiRequest<PropertyScore>(`/markets/${id}/score`, { signal: controller.signal })]).then(([market, score]) => setState({ status: 'ready', market, score })).catch((error: unknown) => { if (error instanceof DOMException && error.name === 'AbortError') return; setState({ status: 'error', message: error instanceof Error ? error.message : 'Market intelligence is unavailable.' }) }); return () => controller.abort() }, [id])
  if (state.status === 'loading') return <MarketDetailState>Reading market history…</MarketDetailState>
  if (state.status === 'error') return <MarketDetailState error>{state.message}</MarketDetailState>
  const { market, score } = state; const latest = market.history.at(0)
  return <main className="market-detail-page"><header className="market-detail-header"><div><DataLabel>01 / Market intelligence</DataLabel><p>{market.country_code} / {market.location_kind} / {market.property_type ?? 'all property'}</p><h1>{market.location_name}</h1></div><div><DataLabel>Median sale price</DataLabel><strong>{formatMoney(latest?.median_sale_price ?? null, latest?.currency ?? null)}</strong><span className={latest?.annual_growth_percent === null || latest?.annual_growth_percent === undefined ? '' : Number(latest.annual_growth_percent) >= 0 ? 'signal--positive' : 'signal--negative'}>{formatPercent(latest?.annual_growth_percent ?? null)} / 12M</span></div></header><section className="market-detail-metrics"><Metric label="Monthly rent" value={formatMoney(latest?.median_rent_monthly ?? null, latest?.currency ?? null)} /><Metric label="Gross yield" value={formatPercent(latest?.gross_yield_percent ?? null)} /><Metric label="Active inventory" value={latest?.active_inventory?.toLocaleString() ?? '—'} /><Metric label="Days on market" value={latest?.days_on_market ?? '—'} /></section><section className="market-history"><div className="section-heading"><div><DataLabel>Historical observations</DataLabel><h2>A market in motion.</h2></div><span>{market.history.length} observations</span></div><MarketChart history={market.history} /></section><section className="market-intelligence"><div><div className="section-heading"><div><DataLabel>Market score</DataLabel><h2>Measured,<br />not assumed.</h2></div><strong>{score.overall_score ?? '—'}</strong></div><div className="score-components">{score.components.map((component) => <details key={component.name}><summary><span>{component.name}</span><strong>{component.score ?? 'N/A'}</strong></summary><p>{component.methodology}</p></details>)}</div></div><aside><DataLabel>Research this market</DataLabel><p>Move from aggregated market signals into the active normalized inventory beneath them.</p><Link to={`/explore?location_id=${market.location_id}${market.property_type ? `&property_type=${market.property_type}` : ''}&limit=20`}>Explore properties ↗</Link><span>Unavailable score components: {score.unavailable_components.join(', ') || 'none'}.</span></aside></section></main>
}
function MarketChart({ history }: { history: MarketMetric[] }) { const points = [...history].reverse(); const values = points.map((point) => Number(point.median_sale_price)).filter(Number.isFinite); if (values.length < 2) return <div className="history-empty">More market observations are required before a trend can be drawn.</div>; const min = Math.min(...values), max = Math.max(...values), spread = max - min || 1; const path = values.map((value, index) => `${index ? 'L' : 'M'} ${(index / (values.length - 1)) * 100} ${94 - ((value - min) / spread) * 82}`).join(' '); return <div className="market-history-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Median market price history"><path d={`${path} L 100 100 L 0 100 Z`} /><path d={path} /></svg><div><span>{points[0]?.observed_on}</span><span>{points.at(-1)?.observed_on}</span></div></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><DataLabel>{label}</DataLabel><strong>{value}</strong></div> }
function MarketDetailState({ children, error = false }: { children: string; error?: boolean }) { return <main className={`market-detail-state${error ? ' market-detail-state--error' : ''}`}>{children}<Link to="/">Return to markets</Link></main> }
