import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/auth-context'
import { DataLabel } from '../components/DataLabel'
import { apiRequest } from '../lib/api'
import { formatMoney, formatPercent } from '../lib/format'
import type { InstrumentDetail } from '../types/instrument'
import type { AlertRule, PropertyHistoryPoint, PropertyListItem, WatchlistDetail, WatchlistSummary } from '../types/property'

interface SavedProperty { itemId: string; property: PropertyListItem; history: PropertyHistoryPoint[] }
interface SavedInstrument { itemId: string; instrument: InstrumentDetail }
type ReadyState = { status: 'ready'; lists: WatchlistSummary[]; active: WatchlistDetail | null; properties: SavedProperty[]; instruments: SavedInstrument[] }
type WatchlistState = { status: 'loading' } | { status: 'error'; message: string } | ReadyState

export function WatchlistPage() {
  const token = useAuth().accessToken
  const [state, setState] = useState<WatchlistState>({ status: 'loading' }); const [selectedId, setSelectedId] = useState<string | null>(null)
  const [newName, setNewName] = useState(''); const [creating, setCreating] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const [alertItemId, setAlertItemId] = useState<string | null>(null); const [alertType, setAlertType] = useState('price_change'); const [alertThreshold, setAlertThreshold] = useState('5')
  useEffect(() => {
    if (!token) return
    const controller = new AbortController(); const headers = { Authorization: `Bearer ${token}` }
    apiRequest<WatchlistSummary[]>('/watchlists', { headers, signal: controller.signal }).then(async (lists) => {
      const target = lists.find((list) => list.id === selectedId) ?? lists[0] ?? null
      if (!target) { setState({ status: 'ready', lists, active: null, properties: [], instruments: [] }); return }
      const active = await apiRequest<WatchlistDetail>(`/watchlists/${target.id}`, { headers, signal: controller.signal })
      const [properties, instruments] = await Promise.all([
        Promise.all(active.items.filter((item) => item.property_id).map(async (item) => { const [property, history] = await Promise.all([apiRequest<PropertyListItem>(`/properties/${item.property_id}`, { signal: controller.signal }), apiRequest<PropertyHistoryPoint[]>(`/properties/${item.property_id}/history?limit=60`, { signal: controller.signal })]); return { itemId: item.id, property, history } })),
        Promise.all(active.items.filter((item) => item.instrument_id).map(async (item) => ({ itemId: item.id, instrument: await apiRequest<InstrumentDetail>(`/instruments/${item.instrument_id}?history_limit=120`, { signal: controller.signal }) }))),
      ])
      setState({ status: 'ready', lists, active, properties, instruments })
    }).catch((error: unknown) => { if (error instanceof DOMException && error.name === 'AbortError') return; setState({ status: 'error', message: error instanceof Error ? error.message : 'Watchlists are unavailable.' }) })
    return () => controller.abort()
  }, [token, selectedId])
  async function createList(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token) return; setCreating(true); try { const list = await apiRequest<WatchlistSummary>('/watchlists', { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: JSON.stringify({ name: newName }) }); setNewName(''); setSelectedId(list.id); setMessage('Watchlist created.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Watchlist could not be created.') } finally { setCreating(false) } }
  async function remove(itemId: string) { if (!token || state.status !== 'ready' || !state.active) return; try { await apiRequest(`/watchlists/${state.active.id}/items/${itemId}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); setState({ ...state, active: { ...state.active, item_count: state.active.item_count - 1, items: state.active.items.filter((item) => item.id !== itemId) }, properties: state.properties.filter((item) => item.itemId !== itemId), instruments: state.instruments.filter((item) => item.itemId !== itemId) }); setMessage('Asset removed.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Asset could not be removed.') } }
  async function createAlert(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!token || !alertItemId) return; const threshold = Number(alertThreshold); if (!Number.isFinite(threshold) || threshold <= 0 || threshold > 100) { setMessage('Set a threshold between 0.01% and 100%.'); return } try { await apiRequest<AlertRule>(`/watchlist-items/${alertItemId}/alert-rules`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: JSON.stringify({ alert_type: alertType, threshold: String(threshold) }) }); setAlertItemId(null); setMessage('Threshold signal enabled. It will appear in Signals.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Signal could not be enabled.') } }
  const actionProps = { alertItemId, alertType, alertThreshold, setAlertItemId, setAlertType, setAlertThreshold, createAlert, remove }
  const empty = state.status === 'ready' && !state.properties.length && !state.instruments.length
  return <main className="watchlist-page"><header className="watchlist-header"><div><DataLabel>03 / Signal ledger</DataLabel><h1>Watch<br />the market.</h1></div><p>Hold opportunities in view without committing capital. Every saved asset remains tied to its latest verified or normalized observation.</p></header><section className="watchlist-controls"><div className="watchlist-tabs">{state.status === 'ready' && state.lists.map((list) => <button type="button" className={(state.active?.id ?? selectedId) === list.id ? 'is-active' : ''} onClick={() => setSelectedId(list.id)} key={list.id}>{list.name}<span>{list.item_count}</span></button>)}</div><form onSubmit={createList}><input required maxLength={100} value={newName} onChange={(event) => setNewName(event.target.value)} placeholder="NEW LIST NAME" aria-label="New watchlist name" /><button disabled={creating} type="submit">{creating ? 'Creating…' : 'Create list +'}</button></form></section>{message && <p className="watchlist-message" role="status">{message}</p>}{state.status === 'loading' && <WatchState>Loading saved signals…</WatchState>}{state.status === 'error' && <WatchState error>{state.message}</WatchState>}{state.status === 'ready' && !state.active && <WatchState>Create your first watchlist, then save assets from Explore.</WatchState>}{state.status === 'ready' && state.active && <section className="watchlist-ledger"><div className="watchlist-ledger__head"><span>Asset</span><span>Price</span><span>Yield</span><span>Change</span><span>Trend</span><span>Action</span></div>{empty ? <WatchState>This watchlist has no saved assets yet.</WatchState> : <>{state.instruments.map(({ itemId, instrument }, index) => <InstrumentEntry key={itemId} itemId={itemId} index={index} instrument={instrument} {...actionProps} />)}{state.properties.map(({ itemId, property, history }, index) => <div className="watchlist-entry" key={itemId}><Link to={`/properties/${property.id}`}><span>{String(index + state.instruments.length + 1).padStart(2, '0')}</span><div><strong>{property.address_line || `${property.property_type} / ${property.location_name}`}</strong><small>{property.location_name}, {property.country_code} · {property.source_name}</small></div></Link><span>{formatMoney(property.price, property.currency)}</span><span>{formatPercent(property.gross_yield_percent)}</span><span>{formatPercent(property.annual_growth_percent)}</span><Sparkline values={[...history].reverse().map((point) => Number(point.asking_price ?? point.estimated_value)).filter(Number.isFinite)} label="Verified property price trend" /><EntryActions itemId={itemId} property {...actionProps} /></div>)}</>}</section>}</main>
}

type ActionProps = { itemId: string; alertItemId: string | null; alertType: string; alertThreshold: string; setAlertItemId: (value: string | null) => void; setAlertType: (value: string) => void; setAlertThreshold: (value: string) => void; createAlert: (event: FormEvent<HTMLFormElement>) => void; remove: (id: string) => void; property?: boolean }
function EntryActions(props: ActionProps) { return <><div className="watchlist-entry__actions"><button type="button" onClick={() => props.setAlertItemId(props.alertItemId === props.itemId ? null : props.itemId)}>{props.alertItemId === props.itemId ? 'Close signal' : 'Add signal'}</button><button type="button" onClick={() => props.remove(props.itemId)}>Remove</button></div>{props.alertItemId === props.itemId && <form className="watchlist-alert-form" onSubmit={props.createAlert}><label><span>Metric</span><select value={props.alertType} onChange={(event) => props.setAlertType(event.target.value)}><option value="price_change">Price change</option>{props.property && <><option value="rent_change">Rent change</option><option value="yield_change">Yield change</option><option value="market_change">Market change</option></>}</select></label><label><span>Movement threshold</span><input required inputMode="decimal" value={props.alertThreshold} onChange={(event) => props.setAlertThreshold(event.target.value)} /><small>%</small></label><button type="submit">Enable signal</button></form>}</> }
function InstrumentEntry({ instrument, index, ...actions }: { instrument: InstrumentDetail; index: number } & ActionProps) { const latest = instrument.history[0]; const history = [...instrument.history].reverse(); const oldest = instrument.history.at(-1); const change = latest?.annual_change_percent ?? (latest && oldest && latest !== oldest ? String((Number(latest.value) / Number(oldest.value) - 1) * 100) : null); const indexValue = instrument.metadata.value_kind === 'index'; return <div className="watchlist-entry"><Link to={instrument.status === 'paper_tradeable' ? `/paper-invest?instrument=${instrument.id}` : '/explore?view=listed'}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{instrument.name}</strong><small>{instrument.symbol ? `${instrument.symbol} · ${instrument.exchange ?? 'LISTED'}` : `${instrument.country_code} · MARKET PROXY`} · {instrument.status.replace('_', ' ')}</small></div></Link><span>{latest ? (indexValue ? `${Number(latest.value).toFixed(1)} pts` : formatMoney(latest.value, latest.currency)) : '—'}</span><span>{formatPercent(latest?.income_yield_percent ?? null)}</span><span>{formatPercent(change)}</span><Sparkline values={history.map((point) => Number(point.value)).filter(Number.isFinite)} label="Verified instrument price trend" /><EntryActions {...actions} /></div> }
function WatchState({ children, error = false }: { children: string; error?: boolean }) { return <div className={`watchlist-state${error ? ' watchlist-state--error' : ''}`}>{children}</div> }
function Sparkline({ values, label }: { values: number[]; label: string }) { if (values.length < 2) return <span className="watchlist-sparkline--empty" title="At least two verified observations are required">Awaiting data</span>; const min = Math.min(...values); const spread = Math.max(...values) - min || 1; const path = values.map((value, index) => `${index ? 'L' : 'M'} ${(index / (values.length - 1)) * 100} ${28 - ((value - min) / spread) * 24}`).join(' '); return <svg className={`watchlist-sparkline${values.at(-1)! >= values[0]! ? '' : ' is-negative'}`} viewBox="0 0 100 32" preserveAspectRatio="none" role="img" aria-label={label}><path d={path} /></svg> }
